<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\ShortUrl;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AdminDashboardController extends Controller
{
    //Admindashboard to view latest 2 clients and 2 latest url generated by  the company members or admins
    public function dashboard(Request $request)
{
    $user = Auth::user();
    if (! $user || ($user->role ?? '') !== 'admin') {
        abort(403, 'Unauthorized');
    }
    $companyName = $user->company->name ?? 'Company';


    $clients = User::where('company_id', $user->company_id)
    ->whereIn('role', ['admin', 'member'])
    ->withCount('shortUrls')
    ->withSum('shortUrls', 'hits')
    ->orderBy('name')
    ->get();

    $visibleClients = $clients->take(2);
    $hiddenClients  = $clients->slice(2);

    $allUrls = ShortUrl::with('user:id,name,email')
        ->where('company_id', $user->company_id)
        ->orderBy('id', 'desc')
        ->get();

    $visibleUrls = $allUrls->take(2);
    $hiddenUrls  = $allUrls->slice(2);
    return view('admindashboard', compact(
        'clients',
        'visibleClients',
        'hiddenClients',
        'visibleUrls',
        'hiddenUrls',
        'companyName'
    ));
}


// ALL URLS for the company when clicking on viewmore from admin dashboard

    public function allUrls()
    {
        $user = Auth::user();
        if (! $user) abort(403, 'Unauthorized');

        // get all urls
        $allUrls = ShortUrl::with('user:id,name,email')
            ->where('company_id', $user->company_id)
            ->orderBy('id', 'desc')
            ->get();

        $shortDomain = env('SHORT_DOMAIN', config('app.url'));

        return view('adminurlsall', compact('allUrls', 'shortDomain'));
    }

  // ALL company colleques(admin/member) for the company when clicking on viewmore from admin dashboard

    public function index(Request $request)
    {
        $user = Auth::user();
        if (! $user) abort(403, 'Unauthorized');

        $clients = User::where('company_id', $user->company_id)
            ->whereIn('role', ['admin', 'member'])
            ->withCount('shortUrls')
            ->withSum('shortUrls', 'hits')
            ->orderBy('name')
            ->get();

        return view('clients.index', [
            'clients' => $clients,
            'mode' => 'admin',
        ]);
    }
}
