<?php

namespace App\Http\Controllers;

use App\Models\ShortUrl;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MemberDashboardController extends Controller
{
    public function dashboard(Request $request)
    {

        //fetch all Urls of generated by  himself
        if ($request->ajax()) {
            return ShortUrl::where('user_id', Auth::id())
                ->orderBy('id', 'desc')
                ->get();
        }

        return view('memberdashboard');
    }
}
